region: us-west-2
s3_bucket: voicebot-matrix-hackathon  # Replace with your bucket name
qa_csv: data/qa_dataset.csv
test_csv: data/test.csv
transcriptions_csv: data/transcriptions.csv
output_csv: output/output.csv

# AWS Services Configuration
transcribe:
  language_code: en-US
  sample_rate: 16000
  channels: 1

polly:
  voice_id: Joanna
  engine: neural

# LLM Configuration
llm:
  provider: bedrock
  model_id: anthropic.claude-3-sonnet-20240229-v1:0
  temperature: 0.7
  max_tokens: 500

# Response Generation
response:
  fuzzy_match_threshold: 80  # minimum score for fuzzy matching
  use_llm_fallback: true     # whether to use LLM when no good match found
